---@meta _
---@class bufferline.DebugOpts
---@field logging boolean
---@class bufferline.GroupOptions
---@field toggle_hidden_on_enter? boolean
---@class bufferline.GroupOpts
---@field options? bufferline.GroupOptions
---@field items bufferline.Group[]
---@class bufferline.Indicator
---@field style? "underline" | "icon" | "none"
---@field icon? string?
---@alias bufferline.Mode 'tabs' | 'buffers'
---@alias bufferline.DiagnosticIndicator fun(count: number, level: string, errors: table<string, any>, ctx: table<string, any>): string
---@alias bufferline.HoverOptions {reveal: string[], delay: integer, enabled: boolean}
---@alias bufferline.IconFetcherOpts {directory: boolean, path: string, extension: string, filetype: string?}
---@class bufferline.Options
---@field public mode? bufferline.Mode
---@field public style_preset? bufferline.StylePreset | bufferline.StylePreset[]
---@field public view? string
---@field public debug? bufferline.DebugOpts
---@field public diagnostics? boolean | 'nvim_lsp' | 'coc'
---@field public diagnostics_indicator? bufferline.DiagnosticIndicator
---@field public diagnostics_update_on_event? boolean        -- legacy immediate refresh behavior
---@field public diagnostics_debounce_ms? number             -- debounce delay for DiagnosticChanged (default 100)
---@field public diagnostics_max_buffers? number|nil         -- cap number of buffers processed per refresh
